#!/usr/bin/env python3
"""make_fixtures.py — build `fixtures_generated.json` from real captures.

Why fixtures are TRIMMED
========================
A search response is ~16 KB of JSON and most of it is signed media URLs:
each ad carries a proxied `video_url` whose path holds a base64'd CDN
address plus a signature, and a `cover_img` with its own. They are kept —
`parse_search` reads both into columns and a fixture without them would
test neither — but nothing else is.

There is no session material to scrub here: the endpoint sets no cookies
at all (measured: zero), and the one header that gates it lives in the
REQUEST, never in the response. That is a happier version of CLAUDE.md
§10 than the sibling repos have: the thing worth not committing is not in
the thing being committed.

Advertiser names ARE real and stay real. An advertiser in a statutory
transparency library is a company that has published its advertising by
law, not a private individual — which is the distinction §10 draws, and
the reason nothing here is replaced with a placeholder.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import asdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from output_writer import Advertisement                   # noqa: E402
from product_parser import parse_search                    # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "fixtures_generated.json")

WANTED = {
    "ads_de_p1.json": ("de_page1", "the first cursor page of a region"),
    "ads_de_p2.json": ("de_page2",
                       "the SECOND page, reached by the cursor — the proof "
                       "that `offset` is not what paginates"),
    "ads_image.json": ("image_ads",
                       "a response containing image ads, which carry a "
                       "`title` and `image_urls` where video ads carry "
                       "neither"),
    "ads_rejected.json": ("rejected",
                          "a response containing a REJECTED ad, with "
                          "TikTok's own policy reason — 2 of 216 measured"),
}


def build(capture_dir: str) -> dict:
    out = {"_readme": (
        "Generated by make_fixtures.py from real TikTok Ad Library "
        "responses. The endpoint sets no cookies and the header that gates "
        "it lives in the request, so there is no session material here to "
        "scrub. Run `python3 make_fixtures.py --verify` to re-check that a "
        "fixture parses identically to its original."), "responses": {}}
    missing = []
    for filename, (name, why) in WANTED.items():
        path = os.path.join(capture_dir, filename)
        if not os.path.exists(path):
            missing.append(filename)
            continue
        out["responses"][name] = {
            "why": why,
            "payload": json.load(open(path, encoding="utf-8")),
        }
    if missing:
        print(f"[!] {len(missing)} capture(s) not found: {missing}",
              file=sys.stderr)
    return out


def verify(capture_dir: str) -> int:
    data = json.load(open(OUT, encoding="utf-8"))
    bad = 0
    for filename, (name, _why) in WANTED.items():
        path = os.path.join(capture_dir, filename)
        entry = data["responses"].get(name)
        if entry is None or not os.path.exists(path):
            print(f"  {name:12} SKIP")
            continue
        original = json.load(open(path, encoding="utf-8"))
        a, da = parse_search(original, "DE", "T", 1, Advertisement)
        b, db = parse_search(entry["payload"], "DE", "T", 1, Advertisement)
        same = ([asdict(r) for r in a] == [asdict(r) for r in b]
                and da.get("total") == db.get("total"))
        print(f"  {name:12} {'OK' if same else 'DIFFERS'}  ({len(a)} row(s))")
        bad += 0 if same else 1
    return 1 if bad else 0


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--captures", default="/home/petr/2scraper/captures/tiktok")
    p.add_argument("--verify", action="store_true")
    args = p.parse_args()
    if args.verify:
        sys.exit(verify(args.captures))
    data = build(args.captures)
    with open(OUT, "w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False, indent=1, sort_keys=True)
    print(f"[+] {len(data['responses'])} fixture(s) -> {OUT} "
          f"({os.path.getsize(OUT):,} bytes)")
