"""product_parser.py — this IS the site.

TikTok's EU Ad Library, and the one header that gates it
========================================================
`library.tiktok.com` is TikTok's advertising transparency library for the
EU/EEA plus the UK, Switzerland, Norway, Iceland, Liechtenstein and
Turkey — 33 regions, listed by the site's own
`/api/v1/support-regions` endpoint rather than guessed.

Its search endpoint is a plain POST and it is served to a bare datacentre
address with no key, no account and no cookies. Measured 2026-09-22 from
Hetzner, Helsinki:

    POST /api/v1/search?region=DE&type=1&start_time=…&end_time=…
        with the browser's headers       HTTP 200, 12 ads
        the same, minus `x-ccl-str`      HTTP 421
        content-type + user-agent +
          referer + x-ccl-str only       HTTP 200, 12 ads

So exactly ONE header gates it, and that header is generated by the page's
own JavaScript. This repo therefore REQUIRES a browser — not to render
anything, but to mint one short-lived token, after which the calls are
plain HTTP. `--transport http` is refused with that reason rather than
failing later with a 421 nobody can interpret.

That makes this repo the odd one of the three: tiktok-profile-scraper and
tiktok-video-scraper both default to plain HTTPS because their pages are
server-rendered, and both treat the browser as a fallback. Here the
browser is a prerequisite, and saying so is the point (CLAUDE.md §21:
gating is per-ROUTE, and the remedy differs with it).

`offset` is a decoy
===================
The request body carries an `offset`, the UI increments it, and it does
NOTHING. Measured: offsets 0, 12 and 24 returned the identical twelve ads,
in the identical order. Pagination is by `search_id`, a base64 cursor the
response hands back:

    {"last_sort": [1790109992000], "next_cursor": 12}

A run that trusted `offset` would re-collect page one for as long as it
was asked to and report a complete run of duplicates — CLAUDE.md §23's
trap, met for the third time in this family and with the loudest decoy
yet, because here the useless parameter is one the site's own UI sends.

`limit` is a decoy too: 12, 50 and 100 all return twelve.
"""

from __future__ import annotations

import base64
import json
import logging
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from tiktok_payload import (BOT_CHALLENGE_MARKERS, PayloadError,
                            WAF_CHALLENGE_MARKERS, decode_page,
                            is_empty_success, waf_markers_present)

logger = logging.getLogger("product_parser")

SOURCE = "library.tiktok.com"

HOST = "library.tiktok.com"
SEARCH_PATH = "/api/v1/search"
REGIONS_PATH = "/api/v1/support-regions?lang=en-US"
UI_URL = "https://library.tiktok.com/ads"

# The header that gates the endpoint. Named here so the engines and the
# suite cannot disagree about it.
TOKEN_HEADER = "x-ccl-str"

# The library's own region list, fetched from `/api/v1/support-regions` on
# 2026-09-22 and kept as a FALLBACK only — the engines ask the site rather
# than trusting this, because a hardcoded list of a living thing rots
# (CLAUDE.md §13). It is here so that `--help` can name them and so a
# typo is refused before a request is spent.
KNOWN_REGIONS = (
    "AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR",
    "GB", "GR", "HR", "HU", "IE", "IS", "IT", "LI", "LT", "LU", "LV", "MT",
    "NL", "NO", "PL", "PT", "RO", "SE", "SI", "SK", "TR",
)

# Ads per response. Not a preference — measured as a ceiling: `limit` 12,
# 50 and 100 all returned twelve.
ADS_PER_PAGE = 12


class NotAnAdsQuery(ValueError):
    """The input is not something this repo can ask the library for.

    Refused WITH THE REASON (CLAUDE.md §5).
    """


def normalise_region(raw: str) -> str:
    """'de', 'DE', 'Germany' -> 'DE', or say why not."""
    s = (raw or "").strip().upper()
    if not s:
        raise NotAnAdsQuery("no region given")
    if s in KNOWN_REGIONS:
        return s
    if s in ("US", "USA", "BR", "CA", "AU", "IN", "JP", "MX"):
        raise NotAnAdsQuery(
            f"{raw!r} is a real country and TikTok's Ad Library does not "
            "cover it. The library is an EU/EEA transparency obligation and "
            "serves 33 regions: the EU, plus GB, CH, NO, IS, LI and TR. "
            "Measured 2026-09-22: region=US and region=BR return a body "
            "that is not JSON at all, while DE, FR and GB return ads.")
    raise NotAnAdsQuery(
        f"{raw!r} is not one of the 33 regions TikTok's Ad Library serves "
        f"({', '.join(KNOWN_REGIONS)})")


def search_url(region: str, start_time: int, end_time: int,
               ad_type: int = 1) -> str:
    """The search endpoint for one region and window."""
    return (f"https://{HOST}{SEARCH_PATH}?region={normalise_region(region)}"
            f"&type={ad_type}&start_time={int(start_time)}"
            f"&end_time={int(end_time)}")


def search_body(query: str = "", cursor: str = "",
                order: str = "create_time,desc") -> Dict[str, Any]:
    """The POST body, with the two decoy parameters set the way the UI
    sets them and NOT relied upon.

    `offset` is sent because the endpoint expects the shape, and is left
    at 0 because it does nothing — see the module docstring. `limit` is
    sent as 12 because that is the measured ceiling; asking for more is
    not an error, it is silently ignored, which is worse.
    """
    return {
        "query": query or "",
        "query_type": "",
        "adv_biz_ids": "",
        "order": order,
        "offset": 0,
        "search_id": cursor or "",
        "limit": ADS_PER_PAGE,
        "ad_type": 0,
        "ad_status": 1,
        "ages": ["all"],
        "ad_reach": ["all"],
        "gender": "ALL",
    }


def decode_cursor(cursor: Optional[str]) -> Optional[Dict[str, Any]]:
    """The base64 cursor, readable — for logs and for the end-of-listing test.

    CLAUDE.md §23 and §24: on three sites now, the response has stated
    which page it actually served, and reading that is the only
    unambiguous end-of-listing signal. Here the cursor says
    `{"last_sort": [...], "next_cursor": N}` and `next_cursor` is the
    count served so far — so a cursor that stops advancing is the listing
    ending, whatever `has_more` claims.
    """
    if not cursor:
        return None
    try:
        padded = cursor + "=" * (-len(cursor) % 4)
        return json.loads(base64.b64decode(padded).decode("utf-8"))
    except Exception:                                     # noqa: BLE001
        return None


def _ms_to_iso(value: Any) -> Optional[str]:
    """TikTok publishes these in MILLISECONDS.

    Read as seconds, 1790112836000 lands in the year 58,700. The factor is
    checked rather than assumed: every value measured is 13 digits, and a
    10-digit one is treated as seconds so a future change is absorbed
    rather than silently mis-dated.
    """
    if isinstance(value, str) and value.strip().isdigit():
        value = int(value)
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        return None
    if value <= 0:
        return None
    seconds = value / 1000.0 if value > 10 ** 11 else float(value)
    try:
        return datetime.fromtimestamp(seconds, tz=timezone.utc).isoformat()
    except (OverflowError, OSError, ValueError):
        return None


def _clean(value: Any) -> Optional[str]:
    if not isinstance(value, str):
        return None
    s = value.strip()
    return s or None


def _int(value: Any) -> Optional[int]:
    if isinstance(value, bool) or value is None:
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, str) and re.fullmatch(r"-?\d+", value.strip()):
        return int(value.strip())
    return None


def ad_url(ad_id: str, region: str) -> str:
    """The library's own page for one ad."""
    return (f"https://{HOST}/ads/detail/?ad_id={ad_id}"
            f"&region={normalise_region(region)}")


def parse_search(payload: Any, region: str, scraped_at: str, page: int,
                 row_cls: Any) -> Tuple[List[Any], Dict[str, Any]]:
    """One search response to rows."""
    if isinstance(payload, (bytes, bytearray, str)):
        try:
            payload = json.loads(decode_page(payload))
        except ValueError as exc:
            raise PayloadError(f"search response did not parse: {exc}") from exc
    if not isinstance(payload, dict):
        raise PayloadError(f"search response is {type(payload).__name__}, "
                           "not an object")

    diag: Dict[str, Any] = {
        "code": payload.get("code"),
        "total": _int(payload.get("total")),
        "has_more": payload.get("has_more"),
        "cursor": payload.get("search_id") or None,
        "cursor_decoded": decode_cursor(payload.get("search_id")),
    }
    ads = payload.get("data")
    if ads is None:
        raise PayloadError(
            f"search response carried no `data` key (keys: {sorted(payload)})")
    if not isinstance(ads, list):
        raise PayloadError(f"`data` is {type(ads).__name__}, not a list")

    rows = []
    for position, ad in enumerate(ads, start=1):
        if not isinstance(ad, dict):
            continue
        ad_id = _clean(ad.get("id"))
        if not ad_id:
            continue
        videos = [v for v in (ad.get("videos") or []) if isinstance(v, dict)]
        video_urls = [_clean(v.get("video_url")) for v in videos]
        video_urls = [u for u in video_urls if u]
        cover_urls = [_clean(v.get("cover_img")) for v in videos]
        cover_urls = [u for u in cover_urls if u]
        images = [_clean(u) for u in (ad.get("image_urls") or [])]
        images = [u for u in images if u]

        # Derived from the creatives the ad actually carries, not from
        # `show_mode` — whose meaning TikTok documents nowhere, and which
        # this repo passes through unchanged rather than guessing at.
        if video_urls and images:
            creative = "video+image"
        elif video_urls:
            creative = "video"
        elif images:
            creative = "image"
        else:
            creative = None

        first = _ms_to_iso(ad.get("first_shown_date"))
        last = _ms_to_iso(ad.get("last_shown_date"))
        days = None
        if first and last:
            try:
                days = max(0, (datetime.fromisoformat(last)
                               - datetime.fromisoformat(first)).days)
            except ValueError:
                days = None

        name = _clean(ad.get("name"))
        own_title = _clean(ad.get("title"))
        rejection = ad.get("rejection_info")
        if isinstance(rejection, (dict, list)):
            # CANONICAL form: sorted keys, fixed separators.
            #
            # Without `sort_keys` this column carries whatever order the
            # source JSON happened to arrive in, and two byte-identical
            # responses can serialise to two different strings — which
            # `diff_runs.py` would then report as the rejection having
            # changed. Found by `make_fixtures.py --verify`, which parsed
            # a capture and its own fixture (equal payloads, `o == f`
            # True) and got different rows: the fixture had been written
            # with sorted keys and the capture had not.
            #
            # Same shape as CLAUDE.md §24's float32 round-trip making two
            # modes disagree on every row — a serialisation detail leaking
            # into a value.
            rejection = json.dumps(rejection, ensure_ascii=False,
                                   sort_keys=True, separators=(", ", ": "))

        rows.append(row_cls(
            source=SOURCE, scraped_at=scraped_at,
            url=ad_url(ad_id, region), sku=ad_id,
            title=own_title or name,

            ad_id=ad_id,
            row_key=f"{normalise_region(region)}:{ad_id}",
            advertiser_name=name,
            region=normalise_region(region),

            first_shown_at=first, last_shown_at=last, days_shown=days,

            creative_type=creative,
            video_count=len(video_urls) or None,
            image_count=len(images) or None,
            video_urls=video_urls or None,
            cover_urls=cover_urls or None,
            image_urls=images or None,

            audit_status=_clean(ad.get("audit_status")),
            sor_audit_status=_clean(ad.get("sor_audit_status")),
            show_mode=_int(ad.get("show_mode")),
            ad_type=_clean(ad.get("type")),
            rejection_info=_clean(rejection) if isinstance(rejection, str)
                           else None,
            estimated_audience=_clean(ad.get("estimated_audience")),

            page=page, position=position,
        ))
    diag["count"] = len(rows)
    return rows, diag


# ---------------------------------------------------------------------------
# Page states
# ---------------------------------------------------------------------------

STATE_CONTENT = "content"
# The query was answered and matched nothing. A real answer.
STATE_NO_ADS = "no_ads"
# HTTP 421: the request reached the endpoint without a usable `x-ccl-str`.
# Its OWN state, because the remedy is its own — mint a fresh token — and
# neither a retry at the same exit nor a rotation will do it.
STATE_TOKEN_REJECTED = "token_rejected"
STATE_EMPTY_SUCCESS = "empty_success"
STATE_CHALLENGE = "challenge"
STATE_WAF_CHALLENGE = "waf_challenge"
STATE_ERROR = "error"
STATE_PARSE_ERROR = "parse_error"
STATE_UNKNOWN = "unknown"


def challenge_markers_present(html: Any) -> List[str]:
    text = decode_page(html)
    return [m for m in BOT_CHALLENGE_MARKERS if m in text]


def detect_page_state(html: Any, status: Optional[int] = None,
                      url: str = "") -> str:
    """Name what the library answered with.

    Accepts a parsed object as well as bytes or text, because the engines'
    `post_json` hands back whatever the transport already decoded. An
    earlier version assumed bytes and died with a `KeyError` on a dict —
    on the first live run, which is where CLAUDE.md §15 says these are
    found.

    The argument ORDER is the contract: every caller writes
    `detect_page_state(body, status, url)` — CLAUDE.md §17, and
    `smoke_test.py` binds every call site against this signature.

    Signals are ordered by how much they PROVE, not by how cheap they are
    (§17's classification-order trap).
    """
    # A parsed object from `post_json`: judged directly, because turning
    # it back into text to re-parse it would be the same guess twice.
    if isinstance(html, (dict, list)):
        if status == 421:
            return STATE_TOKEN_REJECTED
        if status is not None and status >= 400:
            return STATE_ERROR
        if isinstance(html, dict) and "data" in html:
            return STATE_CONTENT if html.get("data") else STATE_NO_ADS
        return STATE_ERROR if isinstance(html, dict) else STATE_UNKNOWN

    if is_empty_success(status, html):
        return STATE_EMPTY_SUCCESS

    # 421 is this endpoint's own way of saying "your token is missing or
    # stale", and it is unambiguous — no body needed.
    if status == 421:
        return STATE_TOKEN_REJECTED

    text = decode_page(html)
    if challenge_markers_present(text):
        return STATE_CHALLENGE
    if waf_markers_present(text):
        return STATE_WAF_CHALLENGE
    if status is not None and status >= 400:
        return STATE_ERROR

    # The payload's own verdict, which outranks anything inferred.
    try:
        data = json.loads(text)
    except ValueError:
        data = None
    if isinstance(data, dict):
        if "data" in data:
            return STATE_CONTENT if data.get("data") else STATE_NO_ADS
        # JSON the endpoint sent that is not a search result — an error
        # envelope, most likely. Named rather than guessed at.
        return STATE_ERROR
    return STATE_UNKNOWN


def page_url(url: str, page: int) -> str:
    """There is no page N of this endpoint, and that is the finding.

    `offset` is present in the body, sent by the site's own UI, and
    IGNORED: offsets 0, 12 and 24 returned the identical twelve ads.
    Pages come from the `search_id` cursor the previous response handed
    back, so page 5's request is unknowable until page 4 has been read —
    which is why `--concurrency` above 1 is refused with that reason
    rather than silently ignored (CLAUDE.md §7).
    """
    if page == 1:
        return url
    raise NotAnAdsQuery(
        "TikTok's Ad Library paginates by an opaque cursor the previous "
        "response hands back, not by an address. Its `offset` parameter is "
        "a decoy — measured, offsets 0, 12 and 24 return the identical "
        "twelve ads — so page URLs cannot be constructed and pages cannot "
        "be fetched independently.")
